version: "3"

services:
  nps:
    image: registry.cn-hangzhou.aliyuncs.com/sxxpqp/nps
    container_name: nps
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - /opt/nps/conf:/conf
