apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-example
  namespace: default
type: Opaque
data:
  url: aHR0cDovL3Byb21ldGhldXMtYWxlcnQtY2VudGVyOjgwODAvcHJvbWV0aGV1c2FsZXJ0P3R5cGU9ZGQmdHBsPXByb21ldGhldXMtZGQ=