kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: frpc
  labels:
    app: frpc
  annotations:
    deprecated.daemonset.template.generation: '7'
    kubesphere.io/creator: sxx
spec:
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frpc
      annotations:
        kubesphere.io/restartedAt: '2023-03-28T10:06:56.898Z'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-kgjoln
          configMap:
            name: frpc
            items:
              - key: frpc.toml
                path: frpc.toml
            defaultMode: 420
      containers:
        - name: container-q2cnta
          image: harbor.iot.store:8085/turing-kubesphere/frpc:v1
          resources: {}
          volumeMounts:
            - name: volume-kgjoln
              readOnly: true
              mountPath: /frp/frpc.toml
              subPath: frpc.toml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: default
      serviceAccount: default
      imagePullSecrets:
        - name: harbor-repository
      hostNetwork: true
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 0
  revisionHistoryLimit: 10
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: frpc
  annotations:
    kubesphere.io/creator: sxx
data:
  frpc.toml: |-
    serverAddr = "zkturing.imwork.net"
    serverPort = 7000
    auth.token = "zkturing.imwork.net"
    transport.protocol = "kcp"

    [[proxies]]
    name = "tcp1_yueyangjiedusuo-tezhijia-mysql"
    type = "tcp"
    localIP = "turingcloud-mysql"
    localPort = 3306
    remotePort = 31006

    [[proxies]]
    name = "tcp1_yueyangjiedusuo-tezhijia-nacos"
    type = "tcp"
    localIP = "turingcloud-register"
    localPort = 8848
    remotePort = 31001

    [[proxies]]
    name = "tcp1_yueyangjiedusuo-tezhijia-redis"
    type = "tcp"
    localIP = "turingcloud-redis"
    localPort = 3306
    remotePort = 31002

    [[proxies]]
    name = "tcp1_yueyangjiedusuo-tezhijia-web"
    type = "tcp"
    localIP = "turingcloud-web"
    localPort = 80
    remotePort = 31003

    [[proxies]]
    name = "tcp1_yueyangjiedusuo-tezhijia-minio"
    type = "tcp"
    localIP = "turingcloud-minio"
    localPort = 9000
    remotePort = 31004


