version: "3.8"
services:
  sub-store:
    image: xream/sub-store
    container_name: sub-store
    restart: always
    environment:
      - SUB_STORE_CRON=50 23 * * *
      - SUB_STORE_FRONTEND_BACKEND_PATH=/T3B9dgzBzdRbBF8Aqx7P
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - /etc/sub-store:/opt/app/data
