apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql_host_cache
spec:
  schedule: "*/10 * * * *" # 每10分钟执行一次
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql_host_cache
            image: mysql:5.7
            args: ['/bin/sh', '-c', 'mysqladmin -u root -p$MYSQL_ROOT_PASSWORD -h $turingcloud-mysql -P 3306 flush-hosts;echo "flush hosts done"']
          restartPolicy: OnFailure
### 或者直接开启mysql的binlog skip-host-cache          