version: "3.7"
services:
  mysql:
    image: docker.io/bitnami/mysql:8.2
    container_name: mysql
    restart: always
    hostname: mysql
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wvp
    ports:
      - "3306:3306"
    networks:
      - mysql
    # 健康检查 端口号要和上面的一致
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
volumes:
  mysql_data: {
    driver: local
  }
networks:
  mysql:
    driver: bridge

    