version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    hostname: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql
    depends_on:
      - mysql
volumes:
  mysql-data: {
    driver: local
  }
networks:
  mysql:
    driver: bridge