# Calico BGP + 内置 LB Installation CR
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    linuxDataplane: Iptables
    bgp: Enabled
    ipPools:
      - name: default-ipv4-ippool
        blockSize: 26
        cidr: REPLACE_POD_CIDR
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all()
