kind: Service
apiVersion: v1
metadata:
  name: pinganjia
  namespace: zhengshang
  annotations:
    kubesphere.io/creator: sxx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ExternalName
  sessionAffinity: None
  externalName: turingcloud-web.kubesphere-system.svc.cluster.local
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    generation: 6
    name: pinganjia
    namespace: zhengshang
  spec:
    rules:
    - host: paj.9ancore.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pinganjia
              port:
                number: 80
    tls:
    - hosts:
      - paj.9ancore.com
      secretName: pinganjia