kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: frpc
  labels:
    app: frpc
  annotations:
    deprecated.daemonset.template.generation: '7'
    kubesphere.io/creator: sxx
spec:
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frpc
      annotations:
        kubesphere.io/restartedAt: '2023-03-28T10:06:56.898Z'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-kgjoln
          configMap:
            name: frpc
            items:
              - key: frpc.ini
                path: frpc.ini
            defaultMode: 420
      containers:
        - name: container-q2cnta
          image: harbor.iot.store:8085/turing-kubesphere/frpc:v1
          resources: {}
          volumeMounts:
            - name: volume-kgjoln
              readOnly: true
              mountPath: /frp/frpc.ini
              subPath: frpc.ini
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: default
      serviceAccount: default
      imagePullSecrets:
        - name: harbor-repository
      hostNetwork: true
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 0
  revisionHistoryLimit: 10
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: frpc
  annotations:
    kubesphere.io/creator: sxx
data:
  frpc.ini: |-
    [common]
    server_addr = zkturing.imwork.net
    server_port = 7000
    token = zkturing.imwork.net
    protocol = kcp
    [tcp1_jiaokeyuan_dangyangmengniu-tezhijia-mysql]
    type = tcp
    local_ip = turingcloud-mysql
    local_port = 3306
    remote_port = 36060
    [tcp1_jiaokeyuan_dangyangmengniu-tezhijia-nacos]
    type = tcp
    local_ip = turingcloud-register
    local_port = 8848
    remote_port = 36061
    [tcp1_jiaokeyuan_dangyangmengniu-tezhijia-redis]
    type = tcp
    local_ip = turingcloud-redis
    local_port = 3306
    remote_port = 36062
    [tcp1_jiaokeyuan_dangyangmengniu-tezhijia-web]
    type = tcp
    local_ip = turingcloud-web
    local_port = 80
    remote_port = 36063
    [tcp1_jiaokeyuan_dangyangmengniu-tezhijia-minio]
    type = tcp
    local_ip = turingcloud-minio
    local_port = 9000
    remote_port = 36064

