version: '3.8'
services:
  gitlab:
    #image: gitlab/gitlab-ce:latest
    image: gitlab/gitlab-ce:18.4.0-ce.0
    container_name: gitlab
    restart: always
    # 建议设置为主机 IP 或实际域名
    hostname: '192.168.150.252' 
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 必须匹配你最终访问的 端口 (9980)
        external_url 'http://192.168.150.252:9980'
        # 告诉 GitLab SSH 实际上是通过宿主机的 9922 转发的
        gitlab_rails['gitlab_shell_ssh_port'] = 9922
    ports:
      - '9980:9980'    # 映射宿主机 9980 到容器 9980
        #- '443:443'    # HTTPS 端口
      - '9922:22'    # 映射宿主机 9922 到容器 22 (SSH)
    volumes:
      # 这里使用了你 docker run 里的绝对路径，确保数据能对应上
      - '/home/gitlab/etc:/etc/gitlab'
      - '/home/gitlab/log:/var/log/gitlab'
      - '/home/gitlab/opt:/var/opt/gitlab'
    shm_size: '256m'