apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 3.11.3
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  
  # 🎯 1. 正常激活 OTLP 接收器的特征开关（这个老版本算子认识）
  enableFeatures:
    - otlp-receiver

  # 🎯 2. 用旧版本算子 100% 认识的 secrets 关键字，把上面的 OTLP 配置文件强行挂载进容器
  # Operator 算子看到这个后，会自动把它作为额外的配置文件合并注入到 prometheus.yml 中
  secrets:
    - prometheus-additional-config

  externalLabels: {}
  image: quay.io/prometheus/prometheus:v3.11.3
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 3.11.3
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceDiscoveryRole: EndpointSlice
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 3.11.3
