apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-config
  namespace: monitoring
stringData:
  otlp-config.yaml: |
    otlp:
      keep_identifying_resource_attributes: true
      promote_resource_attributes:
        - service.instance.id
        - service.name
        - service.namespace
        - deployment.environment.name
        - service.version
        - k8s.cluster.name
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.deployment.name
        - k8s.node.name