apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 3.11.3
  name: k8s
  namespace: monitoring

spec:
  replicas: 2

  image: quay.io/prometheus/prometheus:v3.13.0
  version: 3.11.3

  serviceAccountName: prometheus-k8s

  serviceDiscoveryRole: EndpointSlice

  resources:
    requests:
      memory: 400Mi

  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000

  nodeSelector:
    kubernetes.io/os: linux

  # 开启 OTLP Receiver
  additionalArgs:
    - name: web.enable-otlp-receiver

  alerting:
    alertmanagers:
      - apiVersion: v2
        name: alertmanager-main
        namespace: monitoring
        port: web

  externalLabels: {}

  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 3.11.3

  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  probeNamespaceSelector: {}
  probeSelector: {}

  ruleNamespaceSelector: {}
  ruleSelector: {}

  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}

  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}