# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=root 
    volumes:
      - ./redis:/data
      # - config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net
    # command: redis-server /usr/local/etc/redis/redis.conf
    
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
volumes:
  redis-data:
    driver: local
networks:
  redis-net:
    driver: bridge
