# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=root
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  redis-data:
    driver: local
networks:
  redis-net:
    driver: bridge
