version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      # - config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net
    # command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  redis-data:
    driver: local
networks:
  redis-net:
    driver: bridge
