version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=root 
    volumes:
      - ./redis:/data
      # - config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net
    # command: redis-server /usr/local/etc/redis/redis.conf
    
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
volumes:
  redis-data:
    driver: local
networks:
  redis-net:
    driver: bridge