# Description: Install Ansible on CentOS 7
- hosts: all
  remote_user: root
  tasks:
    - name: install epel
      yum: name=epel-release state=present
# Description: change yum repo to aliyun on CentOS 7
- hosts: all
  remote_user: root
  tasks:
    - name: change yum repo to aliyun
      shell: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && yum makecache    
# Description: install docker on CentOS 7
- hosts: all
  remote_user: root
  tasks:
    - name: install docker
      yum: name=docker state=present
    - name: start docker
      service: name=docker state=started
    - name: enable docker
      service: name=docker enabled=yes
# Description: install docker-compose on CentOS 7
- hosts: all
  remote_user: root
  tasks:
    - name: install docker-compose
      pip: name=docker-compose state=present      