version: '3'

services:
  minio:
    image: registry.cn-hangzhou.aliyuncs.com/sxxpqp/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=sxxpqp.top
      - MINIO_DOMAIN=sxxpqp.top
      # api url
      # - MINIO_API_URL=http://sxxpqp.top:9000
      # 配置console 
      - MINIO_CONSOLE_ADDRESS=https://console.sxxpqp.top
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: